const swaggerAutogen = require('swagger-autogen');
const {baseDir} = require('./config/config');
const config = require('./config/config');

const doc = {
    info: {
        title: 'Lost & Found Service API',
        description: 'Documentation automatically generated by swagger-autogen',
    },
    host: `${config.host}:${config.port}`,
    schemes: ['http'],
    securityDefinitions: {
        bearerAuth: {
            type: 'apiKey',
            name: 'Authorization',
            in: 'header',
            description: 'Enter your bearer token in the format: Bearer <token>',
        },
    },
    security: [
        {
            bearerAuth: [],
        },
    ],
};

const outputFile = `${baseDir}/swagger_output.json`;
const endpointsFiles = ['./server.js'];

swaggerAutogen(outputFile, endpointsFiles, doc).then(() => {
    console.log('Swagger file generated successfully!');
});
